doctrine:
    dbal:
        dbname: '%env(DATABASE_NAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        driver: '%env(DATABASE_DRIVER)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '%env(DATABASE_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            AppDomainEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/infrastructure/persistence/doctrine'
                prefix: 'App\Domain\Entity'
                alias: AppDomainEntity
