version: '3'

services:
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12314
      MYSQL_DATABASE: 'api'

  php:
    build: docker/php
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80
    links:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  rabbitmq:
    build: docker/rabbitmq
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/:rw
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/:rw
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/:rw
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
